### ISSUE TITLE
Incorrect documentation`queued.max.messages.kbytes` documentation

### ISSUE THREAD

**Issue by kevinconaway** [confluentinc/librdkafka#4137]
Description
===========
The [current documentation](https://github.com/confluentinc/librdkafka/blob/39713ae74699dc7bfb61ef1c45b41c153cdf3fc0/CONFIGURATION.md) for the `queued.max.messages.kbytes` field states:

> ... if using the high-level consumer this setting applies to the single consumer queue, regardless of the number of partitions. When using the legacy simple consumer or when separate partition queues are used this setting applies per partition.

Even though we are using the high level consumer we are seeing excessive memory usage when a large value is set and while consuming a large number of partitions.  From looking at the [code](https://github.com/confluentinc/librdkafka/blob/a83cadf5eab3a43f7f0d3dd09f5b1a3e9e88312f/src/rdkafka_fetcher.c#L1030-L1033), it seems that it is checking the value against the per-partition queue, not a single global queue, is that accurate?

Am I misunderstanding the documentation, the code or both here?

**Comment by kevinconaway** [comment]
@edenhill thoughts here?

**Comment by kevinconaway** [comment]
@emasab do you have any thoughts here?

**Comment by emasab** [comment]
Hello @kevinconaway, the max size check is global in case using a consumer group.
When consuming from different partitions independently, it applies to each partition.

> If using the high-level consumer this setting applies to the single consumer queue, regardless of the number of partitions

> When using the legacy simple consumer or when separate partition queues are used this setting applies per partition.

This is because when using the high level consumer the `rktp_fetchq `is forwarded to the single consumer queue, [here](https://github.com/confluentinc/librdkafka/blob/2dff2ebce9dc7e75c0138504b386902384d70eb9/src/rdkafka_assignment.c#L473), so they're the same queue
